/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SplitterConveyor */

#include "splitter_conveyor_lowlevel.h"

JNIEXPORT void JNICALL Java_SplitterConveyor_initializeHardwarePorts(JNIEnv* ignoreEnv, jclass ignorejClass) {
	initializeHardwarePorts();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinder1_getPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SplitterConveyor_cylinder1_1getPosition(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinder1_getPosition();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinder1_moveForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder1_1moveForward(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinder1_moveForward();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinder1_moveBackward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder1_1moveBackward(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinder1_moveBackward();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinder1_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder1_1stop(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinder1_stop();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinder2_getPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SplitterConveyor_cylinder2_1getPosition(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinder2_getPosition();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinder2_moveForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder2_1moveForward(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinder2_moveForward();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinder2_moveBackward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder2_1moveBackward(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinder2_moveBackward();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinder2_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinder2_1stop(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinder2_stop();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinderStart_getPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_SplitterConveyor_cylinderStart_1getPosition(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinderStart_getPosition();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinderStart_moveForward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinderStart_1moveForward(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinderStart_moveForward();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinderStart_moveBackward
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinderStart_1moveBackward(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinderStart_moveBackward();
}

/*
 * Class:     SplitterConveyor
 * Method:    cylinderStart_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_cylinderStart_1stop(JNIEnv* ignoreEnv, jclass ignorejClass) {
	cylinderStart_stop();
}


/*
 * Class:     SplitterConveyor
 * Method:    getIdentificationSensors
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_SplitterConveyor_getIdentificationSensors(JNIEnv* ignoreEnv, jclass ignorejClass) {
	getIdentificationSensors();
}


/*
 * Class:     SplitterConveyor
 * Method:    sensorCylinder1
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_sensorCylinder1 (JNIEnv* ignoreEnv, jclass ignorejClass) {
	sensorCylinder1();
}

/*
 * Class:     SplitterConveyor
 * Method:    sensorCylinder2
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_sensorCylinder2(JNIEnv* ignoreEnv, jclass ignorejClass) {
	sensorCylinder2();
}


/*
 * Class:     SplitterConveyor
 * Method:    conveyorMove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_conveyorMove(JNIEnv* ignoreEnv, jclass ignorejClass) {
	conveyorMove();
}

/*
 * Class:     SplitterConveyor
 * Method:    conveyorstop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_conveyorstop(JNIEnv* ignoreEnv, jclass ignorejClass) {
	conveyorstop();
}

/*
 * Class:     SplitterConveyor
 * Method:    button1_pressed
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_button1_1pressed(JNIEnv* ignoreEnv, jclass ignorejClass) {
	button1_pressed();
}

/*
 * Class:     SplitterConveyor
 * Method:    button2_pressed
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_button2_1pressed(JNIEnv* ignoreEnv, jclass ignorejClass) {
	button2_pressed();
}

/*
 * Class:     SplitterConveyor
 * Method:    buttonEnd_pressed
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_buttonEnd_1pressed(JNIEnv* ignoreEnv, jclass ignorejClass) {
	buttonEnd_pressed();
}

/*
 * Class:     SplitterConveyor
 * Method:    read_Pack_Id_1
 * Signature: ()V
 */
JNIEXPORT jboolean JNICALL Java_SplitterConveyor_read_1Pack_1ID_11(JNIEnv* ignoreEnv, jclass ignorejClass) {
	read_Pack_ID_1();
}

/*
 * Class:     SplitterConveyor
 * Method:    read_Pack_Id_2
 * Signature: ()V
 */

JNIEXPORT jboolean JNICALL Java_SplitterConveyor_read_1Pack_1ID_12(JNIEnv* ignoreEnv, jclass ignorejClass) {
	read_Pack_ID_2();
}


/*
 * Class:     SplitterConveyor
 * Method:    turn_Led_On
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_turn_1Led_1On(JNIEnv* ignoreEnv, jclass ignorejClass) {
	turn_Led_On();
}

/*
 * Class:     SplitterConveyor
 * Method:    turn_Led_Off
 * Signature: ()V
 */

JNIEXPORT void JNICALL Java_SplitterConveyor_turn_1Led_1Off(JNIEnv* ignoreEnv, jclass ignorejClass) {
	turn_Led_Off();
}

/*
 * Class:     SplitterConveyor
 * Method:    verify_Led
 * Signature: ()V
 */

JNIEXPORT jboolean JNICALL Java_SplitterConveyor_verify_1Led(JNIEnv* ignoreEnv, jclass ignorejClass) {
	verify_Led();
}


/*
 * Class:     SplitterConveyor
 * Method:    read_state
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_SplitterConveyor_read_1state(JNIEnv* ignoreEnv, jclass ignorejClass) {
	read_state();
}

/*
 * Class:     SplitterConveyor
 * Method:    rebuild_state
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SplitterConveyor_rebuild_1state(JNIEnv* ignoreEnv, jclass ignorejClass, jint porto) {
	
	rebuild_state(porto);
}





